import { pool } from '../src/db/pool.js';
import { chunkDocumentText } from '../src/services/knowledge-chunking.js';
import { embedDocumentChunks } from '../src/services/embeddings.js';
import { config } from '../src/config.js';

const ownerId = '00000000-0000-4000-8000-000000000001';
const legacyProjectId = '00000000-0000-4000-8000-000000000003';
const projectProfiles = [
  { id: '00000000-0000-4000-8000-000000000101', name: 'Digital Banking & Customer Onboarding', domain: 'Digital Banking', purpose: 'remote deposit account opening and ongoing digital account servicing', actors: 'applicants, verified customers, branch operations staff, and identity-review specialists', records: 'application data, identity evidence, consent receipts, account state, and customer contact preferences', workflow: 'save an application, collect required evidence, perform identity checks, resolve exceptions, and activate an eligible account', exception: 'a name mismatch, unreadable document, duplicate application, or unavailable identity-verification provider', integration: 'the customer identity service, core deposit platform, notification gateway, and case-management queue', measure: 'application completion, identity-check latency, abandonment, and exception resolution time' },
  { id: '00000000-0000-4000-8000-000000000102', name: 'Loan Origination & Credit Assessment', domain: 'Loans and Credit', purpose: 'consumer loan application intake, evidence collection, credit assessment, and decision communication', actors: 'applicants, loan officers, credit analysts, underwriters, and servicing operations staff', records: 'application facts, income evidence, liabilities, bureau responses, policy version, decision rationale, and offer terms', workflow: 'validate an application, obtain permitted evidence, assess affordability and risk, route exceptions, and issue a documented decision', exception: 'missing evidence, conflicting income data, a thin credit file, a policy exception, or a bureau timeout', integration: 'credit bureau services, document intake, identity verification, the loan origination platform, and customer communications', measure: 'decision turnaround, manual referral rate, evidence completeness, and application rework' },
  { id: '00000000-0000-4000-8000-000000000103', name: 'Payment Processing Platform', domain: 'Payments', purpose: 'authenticated initiation, validation, execution, settlement tracking, and reconciliation of customer payments', actors: 'retail and business customers, payment operations, customer support, treasury, and reconciliation analysts', records: 'payment instructions, idempotency keys, authorization evidence, processing state, settlement references, and exception actions', workflow: 'authenticate an instruction, validate limits and beneficiary data, screen risk, submit it once, track outcome, and reconcile settlement', exception: 'duplicate submission, insufficient funds, rejected clearing response, delayed settlement, or an interrupted network exchange', integration: 'core accounts, payment rails, fraud screening, sanctions screening, notifications, and reconciliation services', measure: 'acceptance rate, end-to-end latency, duplicate prevention, settlement breaks, and recoverable failure rate' },
  { id: '00000000-0000-4000-8000-000000000104', name: 'Fraud Detection & Transaction Monitoring', domain: 'Fraud Detection', purpose: 'risk-based transaction monitoring and analyst-led investigation of suspicious activity', actors: 'monitoring services, fraud analysts, investigation leads, customer support, and control owners', records: 'signals, rule and model versions, alert rationale, linked transactions, investigator actions, and dispositions', workflow: 'evaluate a transaction, create a prioritized alert, enrich its context, assign an investigator, and record a supported disposition', exception: 'a delayed signal, duplicate alert, unavailable enrichment source, suspected account takeover, or disputed customer activity', integration: 'payment events, customer profiles, device intelligence, case management, and secure customer contact channels', measure: 'alert latency, useful-alert rate, investigator workload, missed-service events, and disposition completeness' },
  { id: '00000000-0000-4000-8000-000000000105', name: 'Trade Finance / Letter of Credit', domain: 'Trade Finance', purpose: 'documentary letter-of-credit application, examination, amendment, approval, and expiry management', actors: 'importers, exporters, trade operations staff, document examiners, relationship managers, and approvers', records: 'application terms, parties, goods, shipment dates, submitted documents, examination discrepancies, and amendment history', workflow: 'capture instructions, validate parties and terms, examine presented documents, resolve discrepancies, approve actions, and track key dates', exception: 'inconsistent party names, missing originals, a late presentation, conflicting clauses, or an amendment awaiting consent', integration: 'customer due diligence, trade-document intake, sanctions screening, the core trade ledger, and secure messaging', measure: 'examination turnaround, discrepancy rate, expiry risk, amendment cycle time, and complete audit history' },
  { id: '00000000-0000-4000-8000-000000000106', name: 'Insurance Claims Processing', domain: 'Insurance Claims', purpose: 'first notice of loss, evidence collection, coverage assessment, settlement, and claimant communication', actors: 'claimants, contact-centre staff, adjusters, specialist reviewers, repair partners, and payment operations', records: 'policy and claimant details, incident facts, evidence, coverage checks, reserves, decisions, settlement instructions, and contacts', workflow: 'register a claim, validate policy linkage, request evidence, assess coverage and loss, approve within authority, and communicate progress', exception: 'an uncertain policy match, late evidence, a suspected duplicate, inconsistent loss details, or a contested assessment', integration: 'policy administration, document storage, repair networks, payment services, and claimant notifications', measure: 'time to first contact, evidence completion, assessment cycle, reopened claims, and payment accuracy' },
];

const sourceKinds = [
  { suffix: '1', title: 'Stakeholder discovery and service goals', type: 'STAKEHOLDER_STATEMENT', focus: 'business outcomes and user needs' },
  { suffix: '2', title: 'Operational workflow and exception handling', type: 'PROCESS_DESCRIPTION', focus: 'normal processing, handoffs, and recoverable exceptions' },
  { suffix: '3', title: 'Security, privacy, and control workshop', type: 'MEETING_NOTES', focus: 'access control, sensitive data, evidence, and oversight' },
  { suffix: '4', title: 'Reliability, integration, and acceptance notes', type: 'REQUIREMENT_NOTES', focus: 'service levels, dependencies, reconciliation, and acceptance' },
];

function buildInputText(project, source, index) {
  const variant = [
    `Workshop participants described ${project.purpose}. The intended users are ${project.actors}. The service should guide a person through the next useful action, explain what information is required, and retain progress when a task cannot be completed in one session. Operations staff need a clear work queue with ownership, age, and status so that customer-impacting cases do not disappear between teams. These are proposed product behaviors for this synthetic project brief, not a statement of legal obligations.`,
    `The current service depends on ${project.integration}. Each external exchange needs a recorded correlation reference, a bounded timeout, and an outcome that can be reconciled after a retry. A retry must not create a second ${project.records.split(',')[0]} or silently change an earlier decision. When a dependency is unavailable, the interface should distinguish pending work from a definitive rejection, retain enough context for recovery, and make the responsible team visible.`,
    `The team identified ${project.exception} as cases requiring deliberate handling. The system should preserve the original submitted information, show which check or decision is unresolved, and allow an authorized person to record the evidence considered and the reason for an override. A risk signal is an input to review and must not by itself be represented as a confirmed adverse finding. Conflicting instructions should be routed to the designated owner rather than resolved by an undocumented default.`,
    `For this phase, the service should make ${project.measure} observable through operational reports with a stated time window and denominator. The product owner has not yet selected numeric service thresholds, retention periods, or all escalation time limits; those remain decisions for named business and control owners. Acceptance review should use representative normal, boundary, timeout, duplicate, and recovery scenarios. The project assumes existing enterprise identity and secure network services remain available, subject to integration testing.`,
  ][index];
  return [
    `${project.name} — ${source.title}\nPurpose and scope\n${source.focus[0].toUpperCase()}${source.focus.slice(1)} for ${project.purpose}. This source records synthetic discovery material prepared for software requirements analysis. It describes a proposed service boundary, not an approved policy or authoritative compliance interpretation. The initial release should support the core journey and its operational handoffs while leaving policy thresholds configurable by authorized owners.`,
    `Users and business flow\n${variant}\nThe system should make the current case state and next responsible actor apparent to the user. A customer-facing explanation may omit restricted internal details, while a staff view should show permitted evidence and decision history. Users should be able to distinguish saved, submitted, pending, completed, and returned work without inferring that a pending check constitutes approval.`,
    `Information, rules, and exceptions\nThe primary records are ${project.records}. Required fields, permitted values, and validation timing should be confirmed with the business owner. The service must identify missing information before an irreversible transition where practicable, preserve corrections as attributable changes, and prevent one party's case data from appearing in another party's view. An unresolved conflict should remain visible for human resolution; the software should not invent a policy value to make a case pass.`,
    `Quality and control considerations\nAccess should follow named roles and least privilege, with stronger verification for sensitive or high-impact actions. Record actor, timestamp, action, affected record, and relevant external reference for material state changes; protect logs from unauthorized alteration and avoid copying unnecessary sensitive values into diagnostic output. The team must agree a retention and deletion schedule with the relevant records owner before production use. These examples are design considerations, not legal advice.`,
    `Service expectations and open decisions\nThe service should expose health and dependency failures to operations, recover safely after restart, and avoid losing an accepted request when a downstream response is delayed. Product owners must define measurable response-time and availability targets, support hours, recovery objectives, and alert thresholds. Confirm the named approver for exceptions, data-quality ownership, user accessibility needs, and the meaning of ${project.measure}. Validate the assumptions against the selected integration contracts before release.`,
  ].join('\n\n');
}

const knowledge = [
  ['00000000-0000-4000-8000-000000000021','DEMO Practice Note: Identity and Digital Onboarding','CUSTOMER_ONBOARDING_KYC',`DEMO / NON-AUTHORITATIVE PRACTICE NOTE. A digital onboarding team can document which identity attributes are collected, why each is needed, how a person corrects an error, and which verification outcomes require human review. A useful requirement identifies the actor, triggering event, observable result, failure path, and retained evidence. Avoid treating a vendor match score or an unreadable document as a final customer decision without an approved process.\n\nTeams should map account-opening states from draft through submission, verification, exception review, and activation. Access to identity evidence should be limited by role and purpose, with views and exports accounted for. Consent, notice wording, acceptable evidence, retry limits, and retention periods must be confirmed by the organization’s accountable owners. This synthetic note is educational, not legal guidance or a binding control.`],
  ['00000000-0000-4000-8000-000000000022','DEMO Practice Note: Payment Lifecycle and Reconciliation','PAYMENTS',`DEMO / NON-AUTHORITATIVE PRACTICE NOTE. Payment requirements benefit from an explicit lifecycle: received, validated, authorized, submitted, accepted or rejected by the rail, settled, and reconciled. Define which state is customer-visible, which transitions are reversible, and how a delayed response is distinguished from a final failure. A unique idempotency reference and durable correlation identifier help prevent duplicate execution during retry.\n\nOperations should reconcile internal instructions against clearing and settlement outcomes, retain exception ownership, and make unresolved breaks reportable. Security review should address authentication, authorization, payment data exposure, key management, and tamper-evident audit events. This synthetic material is an engineering example only; rail rules and jurisdictional duties require authoritative sources and qualified review.`],
  ['00000000-0000-4000-8000-000000000023','DEMO Practice Note: Credit Application and Decision Evidence','LOANS_CREDIT',`DEMO / NON-AUTHORITATIVE PRACTICE NOTE. A credit workflow can separate application completeness, evidence verification, assessment, exception referral, decision, offer, and customer notification. Preserve the version of the policy or scorecard used, relevant inputs, decision owner, reason codes, and the timestamp at which evidence was considered. A missing bureau response should be represented as unavailable rather than converted into a negative decision.\n\nRequirements should identify which values are customer supplied, externally sourced, calculated, or manually amended. Define review rights, correction paths, access restrictions, and retention with responsible business, risk, privacy, and legal owners. This synthetic note does not state lending law, approval thresholds, or a binding credit policy.`],
  ['00000000-0000-4000-8000-000000000024','DEMO Practice Note: Fraud Alerts and Case Investigation','FRAUD_DETECTION',`DEMO / NON-AUTHORITATIVE PRACTICE NOTE. Monitoring services should record the signal time, transaction reference, rule or model version, risk indicators, and reason an alert was created. Analysts need prioritization, assignment, linked context, a documented disposition, and a way to identify duplicate or related alerts. Separate a suspicion or model output from a confirmed finding and preserve the human rationale for material actions.\n\nOperational measures may include event-to-alert latency, queue age, false-positive review, escalation completeness, and service availability. Sensitive customer context should be available only to authorized investigators and handled through approved contact channels. Thresholds, notification duties, and investigation time limits belong to approved organizational policy; this synthetic example is not authoritative guidance.`],
  ['00000000-0000-4000-8000-000000000025','DEMO Practice Note: Documentary Trade Finance Examination','TRADE_FINANCE',`DEMO / NON-AUTHORITATIVE PRACTICE NOTE. A documentary credit workflow should keep the issued terms, amendments, presented documents, examination findings, approvals, and key dates linked to one case history. Examiners benefit from a checklist tied to the current instruction version and an explicit way to record a discrepancy, seek clarification, or escalate an uncertain interpretation. OCR extraction can assist review but should not silently replace the source document.\n\nParty screening, document access, original-versus-copy handling, presentation timing, and retention should be defined with qualified trade, compliance, records, and legal owners. Capture who examined and approved each material step. This synthetic note is an engineering prompt, not an authoritative statement of trade rules or banking obligations.`],
  ['00000000-0000-4000-8000-000000000026','DEMO Practice Note: Insurance Claim Intake and Assessment','INSURANCE',`DEMO / NON-AUTHORITATIVE PRACTICE NOTE. Claim intake can capture a stable claim reference, policy link, claimant contact preference, incident facts, and a record of evidence requested and received. Assessment workflows should expose coverage checks, reserve changes, specialist referrals, decision rationale, settlement authorization, and communication history as distinct events. A suspected duplicate or inconsistent statement should trigger review rather than an undocumented automatic denial.\n\nClaimants and staff may need different views of the same case. Limit access to sensitive health, financial, and identity information; log material access and amendments; and define secure exchange with repair or payment partners. Service targets, retention periods, and decision authority must be approved by the insurer. This synthetic note is not insurance or legal advice.`],
  ['00000000-0000-4000-8000-000000000027','DEMO Practice Note: Authentication and Access Review','DIGITAL_BANKING',`DEMO / NON-AUTHORITATIVE SECURITY EXAMPLE. Record the user, role, authentication event, requested action, and authorization result for sensitive workflows. Apply least privilege to read, export, approve, amend, and administer permissions as separate capabilities where the risk warrants it. Define how access is granted, reviewed, revoked, and recovered when an identity provider is unavailable.\n\nSensitive actions may require additional verification and clear confirmation of the target record. Service accounts should have named owners and narrowly scoped credentials; secrets should not be stored in source code or written to routine logs. Establish monitoring and incident response with the organization's security team. These are design prompts for discussion, not a certification checklist or binding standard.`],
  ['00000000-0000-4000-8000-000000000028','DEMO Practice Note: Audit Events and Operational Evidence','GENERAL_FINANCIAL',`DEMO / NON-AUTHORITATIVE CONTROL EXAMPLE. For each material business transition, identify the actor or service, event time, affected record, prior and resulting state where appropriate, correlation reference, and reason. Make event definitions consistent across user interface, APIs, and asynchronous workers so support teams can reconstruct a case without relying on mutable screen state. Protect audit records from unauthorized change and separate operational diagnostics from business evidence.\n\nSpecify access, search, export, monitoring, and retention for audit data. Avoid logging credentials, full payment values, or unnecessary identity details. A useful acceptance test verifies an approved change, a denied change, a retry, and a recovery event. Retention and evidentiary sufficiency depend on context and must be set by accountable owners; this synthetic material is not authoritative.`],
  ['00000000-0000-4000-8000-000000000029','DEMO Practice Note: Record Retention and Secure Deletion','GENERAL_FINANCIAL',`DEMO / NON-AUTHORITATIVE RECORDS EXAMPLE. Build a record inventory that names the business purpose, owner, storage location, access class, lifecycle trigger, and approved retention schedule for each data category. Distinguish active case records, audit events, temporary uploads, derived indexes, backups, and legal holds. A deletion workflow should make completion observable across dependent stores and record an appropriate non-sensitive completion event.\n\nRetention periods cannot be safely inferred from a generic technology example. Obtain the applicable schedule and hold rules from the organization's records, privacy, legal, and compliance owners. Ensure search indexes and derived copies follow the same approved lifecycle. This synthetic note contains no authoritative period or legal interpretation.`],
  ['00000000-0000-4000-8000-000000000030','DEMO Practice Note: Compliance Mapping and Source Provenance','REGULATORY_REPORTING',`DEMO / NON-AUTHORITATIVE COMPLIANCE WORKING NOTE. Keep a clear distinction between a project requirement, a control objective, an internal policy, and an external authority. For each proposed mapping, retain the source title, issuing body, version or effective date, relevant passage, jurisdiction, retrieval date, and the reviewer who confirmed applicability. A similarity match is a discovery aid; it does not establish that a source applies or that a system is compliant.\n\nRequirements should state observable system behavior and link to source evidence without copying an unverified legal conclusion. Ask qualified owners to resolve scope, conflicts, exceptions, and update cadence. Synthetic knowledge entries in this demo are deliberately non-authoritative and must never be presented as law, regulation, or binding guidance.`],
];

try {
  await pool.query(`INSERT INTO users(id,display_name,email,role) VALUES($1,'Local Development Owner','owner@local.test','ADMIN') ON CONFLICT(id) DO NOTHING`, [ownerId]);
  // Keep the original deterministic sample and its generated evidence intact, but remove it from the curated demo set.
  await pool.query(`UPDATE projects SET name='Legacy Financial Services Demo Archive',description='Preserved original mixed-domain sample and its historical analysis. New demonstrations use separate domain-specific projects.',status='ARCHIVED',updated_at=now() WHERE id=$1 AND name='Requirements Intelligence Financial Services Demo'`, [legacyProjectId]);

  const allInputs = projectProfiles.flatMap((project, projectIndex) => sourceKinds.map((source, sourceIndex) => ({
    id: `00000000-0000-4000-8000-${String(111 + projectIndex * 10 + sourceIndex).padStart(12, '0')}`,
    project, source, text: buildInputText(project, source, sourceIndex),
  })));
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    for (const project of projectProfiles) {
      const seededProject = await client.query(`INSERT INTO projects(id,name,description,selected_domain,status,owner_id)
        VALUES($1,$2,$3,$4,'ACTIVE',$5) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,selected_domain=EXCLUDED.selected_domain,status='ACTIVE',owner_id=EXCLUDED.owner_id,updated_at=now()
        WHERE projects.owner_id=EXCLUDED.owner_id AND projects.description LIKE 'Synthetic, non-authoritative demo project for %' RETURNING id`, [project.id, project.name, `Synthetic, non-authoritative demo project for ${project.purpose}. Source material is scoped to this project.`, project.domain, ownerId]);
      if (!seededProject.rowCount) throw new Error(`Refusing to manage non-seed project ${project.id}.`);
    }
    for (const input of allInputs) {
      await client.query(`INSERT INTO project_inputs(id,project_id,input_type,title,source,submitted_content,processing_status,created_by)
        VALUES($1,$2,$3,$4,'Deterministic domain demo seed',$5,'READY',$6)
        ON CONFLICT(id) DO UPDATE SET project_id=EXCLUDED.project_id,input_type=EXCLUDED.input_type,title=EXCLUDED.title,source=EXCLUDED.source,submitted_content=EXCLUDED.submitted_content,processing_status='READY',processing_error=NULL,updated_at=now()
        WHERE project_inputs.source='Deterministic domain demo seed'`, [input.id, input.project.id, input.source.type, input.source.title, input.text, ownerId]);
    }
    await client.query('COMMIT');
  } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }

  let chunkCount = 0;
  for (const [id,title,domain,text] of knowledge) {
    const chunks = chunkDocumentText(text, { maxChars: 700, overlapChars: 75 });
    const vectors = await embedDocumentChunks(chunks, title);
    const kb = await pool.connect();
    try {
      await kb.query('BEGIN');
      const document = await kb.query(`INSERT INTO knowledge_documents(id,title,source,document_type,financial_domain,jurisdiction,version,authority,tags,original_filename,mime_type,file_size_bytes,storage_key,extracted_text,processing_status)
        VALUES($1,$2,'Local synthetic demo corpus','ORGANIZATIONAL_POLICY',$3,NULL,'demo-v1','DEMO / NON-AUTHORITATIVE',ARRAY['demo','non-authoritative','requirements-intelligence'],'demo-note.txt','text/plain',$4,$5,$6,'READY')
        ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,source=EXCLUDED.source,document_type=EXCLUDED.document_type,financial_domain=EXCLUDED.financial_domain,version=EXCLUDED.version,authority=EXCLUDED.authority,tags=EXCLUDED.tags,extracted_text=EXCLUDED.extracted_text,processing_status='READY',updated_at=now()
        WHERE knowledge_documents.source='Local demo corpus' OR knowledge_documents.source='Local synthetic demo corpus' RETURNING id`, [id,title,domain,text.length,`demo-${id}`,text]);
      if (document.rowCount) {
        await kb.query('DELETE FROM knowledge_chunks WHERE knowledge_document_id=$1 AND chunk_index >= $2', [id, chunks.length]);
        for (let i=0;i<chunks.length;i++) await kb.query(`INSERT INTO knowledge_chunks(knowledge_document_id,chunk_index,chunk_text,chunk_metadata,embedding,embedding_model)
          VALUES($1,$2,$3,$4,$5::vector,$6) ON CONFLICT(knowledge_document_id,chunk_index) DO UPDATE SET chunk_text=EXCLUDED.chunk_text,chunk_metadata=EXCLUDED.chunk_metadata,embedding=EXCLUDED.embedding,embedding_model=EXCLUDED.embedding_model,updated_at=now()`, [id,i,chunks[i].chunkText,chunks[i].metadata,`[${vectors[i].join(',')}]`,config.knowledge.embeddingModel]);
        chunkCount += chunks.length;
      }
      await kb.query('COMMIT');
    } catch (error) { await kb.query('ROLLBACK'); throw error; } finally { kb.release(); }
  }
  console.log(`Seeded ${projectProfiles.length} domain projects with ${allInputs.length} READY inputs (${Math.min(...allInputs.map((x)=>x.text.length))}-${Math.max(...allInputs.map((x)=>x.text.length))} characters each) and ${knowledge.length} non-authoritative KB documents (${chunkCount} chunks).`);
} catch (error) { console.error(`Demo seed failed: ${error.message}`); process.exitCode=1; }
finally { await pool.end(); }
